### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by claudiogbarreto** [adxsoft/MapInsight#1]
I think there is a little mistake in line 270:

Unexpected input: '(note,,' at line: 270, column: 24

note=wordwrap(note,,wrapafterchars,wrapcharacter).trim()

The correct is 

note=wordwrap(note,wrapafterchars,wrapcharacter).trim()

**Comment by adxsoft** [comment]
Hi Claudio
Thanks for finding this bug. It is now corrected in _**MapInsight_V1_2.groovy**_ 
Rgds
Allan
